BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[SyncHistory] (
    [id] NVARCHAR(1000) NOT NULL,
    [version] NVARCHAR(1000) NOT NULL,
    [generatedAt] DATETIME2 NOT NULL,
    [syncedAt] DATETIME2 NOT NULL CONSTRAINT [SyncHistory_syncedAt_df] DEFAULT CURRENT_TIMESTAMP,
    [success] BIT NOT NULL,
    CONSTRAINT [SyncHistory_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
